name: RT-Thread

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  # Runs at 16:00 UTC (BeiJing 00:00) on the 1st of every month
  schedule:
    - cron:  '0 16 1 * *'
  push:
    branches:
      - master
    paths-ignore:
      - documentation/**
      - '**/README.md'
      - '**/README_zh.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - documentation/**
      - '**/README.md'
      - '**/README_zh.md'

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:
    runs-on: ubuntu-20.04
    #container:
     # image: ghcr.io/lt6210925/publish-packages/game:sha-bc39929
      #options: '--entrypoint /bin/bash'
    name: ${{ matrix.legs.RTT_BSP }}
    strategy:
      fail-fast: false
      matrix:
       legs:
         - {RTT_BSP: "qemu-vexpress-a9", RTT_TOOL_CHAIN: "sourcery-arm",SUB_RTT_BSP: ["stm32/stm32f103-100ask-mini","stm32/stm32f072-st-nucleo"]}
    steps:
     # - uses: actions/checkout@v3
      #- name: Set up Python
       # uses: actions/setup-python@v3
        #with:
         # python-version: 3.8

      - name: Bsp Scons Compile
        shell: bash
        env:
          SRTT_BSP: ${matrix.legs.SUB_RTT_BSP[*]}
          RTT_TOOL_CHAIN: ${{ matrix.legs.RTT_TOOL_CHAIN }}
        run: |
          ls ~ -la
          pwd
          echo ${{ matrix.legs.SUB_RTT_BSP[1] }}
          echo $SRTT_BSP
          
          for dir in ${{ matrix.legs.SUB_RTT_BSP }}; do
              dir_name=$(basename "$dir")
              echo "========================Current directory: $dir_name================="
             # cd "$dir"
              ##scons -j8
              #cd ..
          done
